In [1]:
#librerias
import pandas as pd

In [ ]:
directorio = r"C:\Users\DETPC\Downloads\yellow_tripdata_2025-01.parquet"
datos_crudos = pd.read_parquet(directorio)

print(f'Columnas: {datos_crudos.columns}') 
print(datos_crudos.shape[1])

Columnas: Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')
20

In [6]:
datos_crudos.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0
5,2,2025-01-01 00:48:24,2025-01-01 01:08:26,2.0,2.63,1.0,N,239,68,2,19.1,1.0,0.5,0.00,0.0,1.0,24.10,2.5,0.0,0.0
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.40,1.0,N,170,170,1,4.4,3.5,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.0
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.60,1.0,N,234,148,1,12.1,3.5,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.0
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.80,1.0,N,148,170,1,19.1,3.5,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.0
9,2,2025-01-01 00:00:02,2025-01-01 00:09:36,1.0,1.71,1.0,N,237,262,2,11.4,1.0,0.5,0.00,0.0,1.0,16.40,2.5,0.0,0.0

##### Repetidos

In [333]:
# duplicados exactos (todas las columnas idénticas)
duplicados_exactos = datos_crudos.duplicated().sum()

# duplicados lógicos 
# (Mismo vendedor, misma hora de inicio y mismo destino)
columnas_clave = ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'DOLocationID', 'total_amount']
duplicados_logicos = datos_crudos.duplicated(subset=columnas_clave).sum()

print(f"Filas que son copias exactas: {duplicados_exactos}")
print(f"Filas identicas por logica: {duplicados_logicos}")

if duplicados_logicos > 0:
    duplicados_df = datos_crudos[datos_crudos.duplicated(subset=columnas_clave, keep=False)]

Filas que son copias exactas: 0
Filas identicas por logica: 3

In [334]:
duplicados_df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1800351,1,2025-01-20 16:55:30,2025-01-20 17:01:39,2.0,0.70,1.0,N,236,237,1,7.20,2.5,0.5,1.00,0.0,1.0,12.20,2.5,0.0,0.00
1802707,1,2025-01-20 16:55:30,2025-01-20 17:01:39,1.0,1.00,1.0,N,142,237,1,7.20,2.5,0.5,1.00,0.0,1.0,12.20,2.5,0.0,0.00
2016697,2,2025-01-22 21:56:45,2025-01-22 22:06:56,3.0,1.42,1.0,N,163,233,1,10.70,1.0,0.5,3.29,0.0,1.0,19.74,2.5,0.0,0.75
2020140,2,2025-01-22 21:56:45,2025-01-22 22:06:56,1.0,1.34,1.0,N,163,233,1,10.70,1.0,0.5,3.29,0.0,1.0,19.74,2.5,0.0,0.75
3323121,2,2025-01-24 19:40:00,2025-01-24 19:51:00,NaN,1.11,NaN,None,137,186,0,-4.75,0.0,0.5,0.00,0.0,1.0,2.00,NaN,NaN,0.75
3324450,2,2025-01-24 19:40:00,2025-01-24 19:51:00,NaN,0.94,NaN,None,170,186,0,-4.75,0.0,0.5,0.00,0.0,1.0,2.00,NaN,NaN,0.75

##### Vendedor

In [404]:
print(datos_crudos.VendorID.shape[0])
print(datos_crudos.VendorID.value_counts().sum())
print(datos_crudos.VendorID.value_counts())

3475226
3475226
VendorID
2    2719860
1     753671
7       1206
6        489
Name: count, dtype: int64

##### Pasajeros

In [328]:
print(datos_crudos.passenger_count.shape[0])
print(datos_crudos.passenger_count.value_counts().sum())
print(datos_crudos.passenger_count.value_counts())

3475226
2935077
passenger_count
1.0    2322434
2.0     407761
3.0      91409
4.0      59009
0.0      24656
5.0      17786
6.0      12004
8.0         11
7.0          4
9.0          3
Name: count, dtype: int64

In [330]:
print("Total Nulos:")
print(datos_crudos.passenger_count.isnull().sum())
print(f"Porcentaje nulos: {datos_crudos.passenger_count.isnull().sum()/datos_crudos.shape[0]*100:.2f}%")

Total Nulos:
540149
Porcentaje nulos: 15.54%

###### pasajeros cero

In [332]:
sin_pasajeros = datos_crudos[datos_crudos['passenger_count'] == 0]
sin_pasajeros

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.4,1.0,N,170,170,1,4.4,3.50,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.00
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.6,1.0,N,234,148,1,12.1,3.50,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.00
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.8,1.0,N,148,170,1,19.1,3.50,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.00
94,1,2025-01-01 00:11:27,2025-01-01 00:16:58,0.0,0.7,1.0,N,144,211,1,7.2,3.50,0.5,0.00,0.0,1.0,12.20,2.5,0.0,0.00
95,1,2025-01-01 00:19:30,2025-01-01 00:27:25,0.0,1.0,1.0,N,211,158,1,9.3,3.50,0.5,2.85,0.0,1.0,17.15,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933984,1,2025-01-31 23:20:45,2025-01-31 23:45:28,0.0,3.9,1.0,N,144,50,1,25.4,4.25,0.5,2.50,0.0,1.0,33.65,2.5,0.0,0.75
2934049,1,2025-01-31 23:54:49,2025-02-01 00:09:35,0.0,6.4,1.0,N,263,232,1,28.2,4.25,0.5,2.00,0.0,1.0,35.95,2.5,0.0,0.75
2934589,1,2025-01-31 23:16:04,2025-01-31 23:36:38,0.0,2.4,1.0,N,68,114,1,15.6,4.25,0.5,4.25,0.0,1.0,25.60,2.5,0.0,0.75
2934590,1,2025-01-31 23:57:51,2025-02-01 00:08:06,0.0,1.6,1.0,N,142,236,1,10.7,3.50,0.5,3.10,0.0,1.0,18.80,2.5,0.0,0.00
2934894,1,2025-01-31 23:11:52,2025-01-31 23:37:36,0.0,6.3,1.0,N,68,112,1,29.6,4.25,0.5,5.00,0.0,1.0,40.35,2.5,0.0,0.75

In [406]:
sin_pasajeros['VendorID'].value_counts()

VendorID
1    24579
2       77
Name: count, dtype: int64

In [410]:
sin_pasajeros[sin_pasajeros['trip_distance'] == 0].shape[0]

1000

In [425]:
sin_distancia_sin_pasajeros = sin_pasajeros[sin_pasajeros['trip_distance'] == 0]
sin_distancia_sin_pasajeros

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
706,1,2025-01-01 00:42:42,2025-01-01 00:42:44,0.0,0.0,1.0,N,261,261,1,3.0,3.50,0.5,2.35,0.0,1.0,10.35,2.5,0.0,0.00
8747,1,2025-01-01 01:42:36,2025-01-01 01:44:12,0.0,0.0,1.0,N,164,164,3,3.7,3.50,0.5,0.00,0.0,1.0,8.70,2.5,0.0,0.00
9621,2,2025-01-01 01:45:42,2025-01-01 01:45:57,0.0,0.0,5.0,N,140,140,2,15.2,0.00,0.5,0.00,0.0,1.0,19.20,2.5,0.0,0.00
9622,2,2025-01-01 01:47:54,2025-01-01 01:48:13,0.0,0.0,5.0,N,140,140,1,15.2,0.00,0.5,4.80,0.0,1.0,24.00,2.5,0.0,0.00
13901,1,2025-01-01 02:24:16,2025-01-01 02:24:19,0.0,0.0,1.0,N,170,170,1,3.0,3.50,0.5,32.00,0.0,1.0,40.00,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2919110,1,2025-01-31 21:50:39,2025-01-31 21:50:39,0.0,0.0,99.0,Y,142,264,1,23.2,0.00,0.0,0.00,0.0,0.0,23.20,0.0,0.0,0.00
2920407,1,2025-01-31 21:04:35,2025-01-31 21:04:45,0.0,0.0,1.0,N,162,162,3,3.0,4.25,0.5,0.00,0.0,1.0,8.75,2.5,0.0,0.75
2920408,1,2025-01-31 21:05:16,2025-01-31 21:05:28,0.0,0.0,2.0,N,162,162,2,70.0,3.25,0.5,0.00,7.0,1.0,81.75,2.5,0.0,0.75
2924430,1,2025-01-31 22:12:37,2025-01-31 22:12:58,0.0,0.0,5.0,N,87,87,4,10.0,0.75,0.0,0.00,0.0,1.0,11.75,0.0,0.0,0.75
2930297,2,2025-01-31 22:59:09,2025-01-31 23:01:27,0.0,0.0,5.0,N,255,255,1,6.8,0.00,0.5,1.66,0.0,1.0,9.96,0.0,0.0,0.00

In [411]:
sin_pasajeros[sin_pasajeros['fare_amount'] == 0].shape[0]

34

In [414]:
sin_pasajeros[(sin_pasajeros['fare_amount'] == 0) & (sin_pasajeros['trip_distance'] == 0)].shape[0]

14

In [426]:
sin_pasajeros[(sin_pasajeros['PULocationID'] == sin_pasajeros['DOLocationID'])].shape[0]

1981

In [417]:
sin_pasajeros['store_and_fwd_flag'].value_counts()

store_and_fwd_flag
N    24120
Y      536
Name: count, dtype: int64

###### Nulos

In [419]:
pasajeros_nulos = datos_crudos[datos_crudos['passenger_count'].isnull()]
pasajeros_nulos

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,2.32,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,6.02,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,22.72,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,-2.35,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,5.06,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [421]:
pasajeros_nulos.payment_type.value_counts()

payment_type
0    540149
Name: count, dtype: int64

In [422]:
pasajeros_nulos[pasajeros_nulos['trip_distance'] == 0].shape[0]

51983

In [423]:
pasajeros_nulos[pasajeros_nulos['fare_amount'] == 0].shape[0]

39

In [424]:
pasajeros_nulos[(pasajeros_nulos['fare_amount'] == 0) & (pasajeros_nulos['trip_distance'] == 0)].shape[0]

11

##### Distancia

In [429]:
print(datos_crudos.trip_distance.shape[0])
print(datos_crudos.trip_distance.value_counts().sum())
#print(datos_crudos.trip_distance.value_counts())
distancia_mayor =datos_crudos['trip_distance'].value_counts().sort_index(ascending=False)
distancia_mayor

3475226
3475226

trip_distance
276423.57        1
276099.95        1
222167.49        1
206137.99        1
202771.63        1
             ...
0.04          1252
0.03          1603
0.02          3546
0.01         11118
0.00         90893
Name: count, Length: 4545, dtype: int64

In [432]:
distancia_no_cancelada = datos_crudos[datos_crudos['PULocationID'] != datos_crudos['DOLocationID']]
distancia_no_cancelada

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.00,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.10,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.80,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.00
5,2,2025-01-01 00:48:24,2025-01-01 01:08:26,2.0,2.63,1.0,N,239,68,2,19.10,1.0,0.5,0.00,0.0,1.0,24.10,2.5,0.0,0.00
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.60,1.0,N,234,148,1,12.10,3.5,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.00,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.00,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.00,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.00,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.00,0.0,1.0,16.09,NaN,NaN,0.00

In [437]:
distancia_discrepancia = distancia_no_cancelada[distancia_no_cancelada['trip_distance'] >=302]
distancia_discrepancia

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
420874,2,2025-01-06 08:18:30,2025-01-06 08:33:49,1.0,1472.37,1.0,N,140,236,1,15.60,0.0,0.5,0.98,0.0,1.0,20.58,2.5,0.00,0.00
660429,2,2025-01-08 19:11:56,2025-01-08 19:36:50,1.0,1847.61,1.0,N,237,234,1,22.60,7.5,0.5,8.52,0.0,1.0,43.37,2.5,0.00,0.75
708849,2,2025-01-09 12:19:06,2025-01-09 13:14:26,1.0,4020.04,4.0,N,132,25,1,82.80,0.0,0.5,15.00,0.0,1.0,101.05,0.0,1.75,0.00
1126293,2,2025-01-13 17:04:40,2025-01-13 17:15:42,1.0,2001.95,1.0,N,229,143,2,12.10,2.5,0.5,0.00,0.0,1.0,19.35,2.5,0.00,0.75
2633889,1,2025-01-29 09:13:51,2025-01-29 11:17:39,1.0,44730.30,99.0,N,72,140,1,44.50,0.0,0.5,0.00,0.0,0.0,45.00,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446937,2,2025-01-31 07:33:00,2025-01-31 07:54:00,NaN,135116.83,NaN,None,239,13,0,31.77,0.0,0.5,0.00,0.0,1.0,36.52,NaN,NaN,0.75
3461154,2,2025-01-31 18:33:00,2025-01-31 18:53:00,NaN,71976.78,NaN,None,41,243,0,28.08,0.0,0.5,0.00,0.0,1.0,29.58,NaN,NaN,0.00
3461434,2,2025-01-31 18:13:00,2025-01-31 18:21:00,NaN,88102.25,NaN,None,48,161,0,-4.75,0.0,0.5,0.00,0.0,1.0,5.08,NaN,NaN,0.75
3464668,2,2025-01-31 19:24:00,2025-01-31 19:35:00,NaN,60677.15,NaN,None,170,113,0,10.16,0.0,0.5,0.00,0.0,1.0,14.91,NaN,NaN,0.75
3470452,2,2025-01-31 22:06:00,2025-01-31 22:16:00,NaN,19060.56,NaN,None,238,41,0,15.72,0.0,0.5,2.96,0.0,1.0,22.68,NaN,NaN,0.00

In [441]:
distancia_discrepancia[distancia_discrepancia['fare_amount'] == 0].shape[0]

0

In [444]:
distancia_discrepancia[distancia_discrepancia['PULocationID'] == distancia_discrepancia['DOLocationID']].shape[0]

0

##### Código de tarifa final vigente

In [446]:
print(datos_crudos.RatecodeID.shape[0])
print(datos_crudos.RatecodeID.value_counts().sum())
print(datos_crudos.RatecodeID.value_counts())

3475226
2935077
RatecodeID
1.0     2756472
2.0       94420
99.0      41963
5.0       26501
3.0        8622
4.0        7092
6.0           7
Name: count, dtype: int64

In [ ]:
print("Total Nulos:")
print(datos_crudos.RatecodeID.isnull().sum())
print(f"Porcentaje nulos: {datos_crudos.RatecodeID.isnull().sum()/datos_crudos.shape[0]*100:.2f}%")

Total Nulos:
540149
Porcentaje nulos: 15.54%

In [449]:
tarifa_nula = datos_crudos[datos_crudos['RatecodeID'].isnull()]
tarifa_nula

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,2.32,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,6.02,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,22.72,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,-2.35,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,5.06,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [450]:
tarifa_nula.passenger_count.value_counts()

Series([], Name: count, dtype: int64)

In [451]:
tarifa_nula.payment_type.value_counts()

payment_type
0    540149
Name: count, dtype: int64

In [455]:
tarifa_nula.query("DOLocationID == PULocationID").shape[0]

14318

##### Bandera indicadora

In [456]:
print(datos_crudos.store_and_fwd_flag.shape[0])
print(datos_crudos.store_and_fwd_flag.value_counts().sum())
print(datos_crudos.store_and_fwd_flag.value_counts())

3475226
2935077
store_and_fwd_flag
N    2927431
Y       7646
Name: count, dtype: int64

In [457]:
print("Total Nulos:")
print(datos_crudos.store_and_fwd_flag.isnull().sum())
print(f"Porcentaje nulos: {datos_crudos.store_and_fwd_flag.isnull().sum()/datos_crudos.shape[0]*100:.2f}%")

Total Nulos:
540149
Porcentaje nulos: 15.54%

In [459]:
bandera_nula = datos_crudos[datos_crudos['store_and_fwd_flag'].isnull()]
bandera_nula

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,2.32,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,6.02,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,22.72,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,-2.35,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,5.06,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [462]:
bandera_nula.payment_type.value_counts()

payment_type
0    540149
Name: count, dtype: int64

##### Tipo de pago

In [463]:
print(datos_crudos.payment_type.shape[0])
print(datos_crudos.payment_type.value_counts().sum())
print(datos_crudos.payment_type.value_counts())

3475226
3475226
payment_type
1    2444393
0     540149
2     390429
4      76481
3      23773
5          1
Name: count, dtype: int64

##### Tiempo distancia - calculo base

In [464]:
print(datos_crudos.fare_amount.shape[0])
print(datos_crudos.fare_amount.value_counts().sum())
print(datos_crudos.fare_amount.value_counts())

3475226
3475226
fare_amount
8.60     150277
7.90     150262
9.30     147090
7.20     144202
10.00    142048
          ...
69.06         1
60.79         1
70.16         1
63.40         1
65.12         1
Name: count, Length: 11538, dtype: int64

In [465]:
tiempo_distancia =datos_crudos['fare_amount'].value_counts().sort_index(ascending=False)
tiempo_distancia

fare_amount
 863372.12    1
 2450.90      1
 1309.20      1
 950.00       3
 936.80       1
             ..
-634.40       1
-700.00       5
-826.20       1
-850.00       1
-900.00       1
Name: count, Length: 11538, dtype: int64

In [466]:
tiempo_distancia_negativo =datos_crudos.query("fare_amount < 0")
tiempo_distancia_negativo

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.20,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.00
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.50,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.00
104,2,2025-01-01 00:56:12,2025-01-01 01:15:00,1.0,0.97,1.0,N,161,170,4,-16.30,-1.0,-0.5,0.00,0.0,-1.0,-21.30,-2.5,0.0,0.00
149,2,2025-01-01 00:55:53,2025-01-01 01:06:49,1.0,1.42,1.0,N,79,45,2,-12.10,-1.0,-0.5,0.00,0.0,-1.0,-17.10,-2.5,0.0,0.00
202,2,2025-01-01 00:29:35,2025-01-01 00:36:02,1.0,0.60,1.0,N,79,148,4,-7.20,-1.0,-0.5,0.00,0.0,-1.0,-12.20,-2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475198,2,2025-01-31 23:30:26,2025-01-31 23:36:41,NaN,1.21,NaN,None,49,17,0,-1.50,0.0,0.5,0.00,0.0,1.0,1.00,NaN,NaN,0.00
3475204,2,2025-01-31 23:33:05,2025-01-31 23:46:21,NaN,2.55,NaN,None,144,170,0,-4.75,0.0,0.5,0.00,0.0,1.0,4.91,NaN,NaN,0.75
3475205,2,2025-01-31 23:43:55,2025-01-31 23:48:40,NaN,0.45,NaN,None,231,45,0,-4.75,0.0,0.5,0.00,0.0,1.0,3.00,NaN,NaN,0.75
3475212,2,2025-01-31 23:00:46,2025-01-31 23:12:08,NaN,1.51,NaN,None,230,229,0,-4.75,0.0,0.5,0.00,0.0,1.0,2.07,NaN,NaN,0.75
3475217,2,2025-01-31 23:38:25,2025-01-31 23:46:15,NaN,1.34,NaN,None,234,100,0,-4.75,0.0,0.5,0.00,0.0,1.0,5.00,NaN,NaN,0.75

In [479]:
tiempo_distancia_negativo_anulado = tiempo_distancia_negativo.query("(PULocationID == DOLocationID) & (trip_distance == 0)")
tiempo_distancia_negativo_anulado

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
3482,2,2025-01-01 00:07:03,2025-01-01 00:07:10,1.0,0.0,1.0,N,260,260,4,-3.00,-1.00,-0.5,0.0,0.0,-1.0,-5.50,0.0,0.00,0.00
3836,2,2025-01-01 00:51:49,2025-01-01 00:52:20,1.0,0.0,5.0,N,90,90,4,-5.00,0.00,0.0,0.0,0.0,-1.0,-8.50,-2.5,0.00,0.00
3839,2,2025-01-01 00:41:17,2025-01-01 00:41:21,1.0,0.0,2.0,N,163,163,4,-70.00,0.00,-0.5,0.0,0.0,-1.0,-74.00,-2.5,0.00,0.00
4859,2,2025-01-01 00:16:11,2025-01-01 00:16:29,1.0,0.0,1.0,N,148,148,2,-3.00,-1.00,-0.5,0.0,0.0,-1.0,-8.00,-2.5,0.00,0.00
5304,2,2025-01-01 00:48:58,2025-01-01 00:49:14,2.0,0.0,5.0,N,137,137,3,-28.20,-4.25,-0.5,0.0,0.0,-1.0,-38.20,-2.5,-1.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3464498,2,2025-01-31 19:00:13,2025-01-31 19:03:05,NaN,0.0,NaN,None,234,234,0,-4.75,0.00,0.5,0.0,0.0,1.0,7.08,NaN,NaN,0.75
3464907,2,2025-01-31 19:27:30,2025-01-31 19:31:59,NaN,0.0,NaN,None,237,237,0,-4.00,0.00,0.5,0.0,0.0,1.0,3.52,NaN,NaN,0.00
3466133,2,2025-01-31 19:52:43,2025-01-31 19:55:02,NaN,0.0,NaN,None,224,224,0,-4.75,0.00,0.5,0.0,0.0,1.0,1.00,NaN,NaN,0.75
3467522,2,2025-01-31 20:38:33,2025-01-31 20:38:58,NaN,0.0,NaN,None,237,237,0,-4.00,0.00,0.5,0.0,0.0,1.0,3.33,NaN,NaN,0.00
3468200,2,2025-01-31 20:11:23,2025-01-31 20:11:40,NaN,0.0,NaN,None,107,107,0,-4.75,0.00,0.5,0.0,0.0,1.0,3.23,NaN,NaN,0.75

In [506]:
tiempo_distancia_positiva = datos_crudos.query("(fare_amount > 800) & (trip_distance < 300) & (RatecodeID !=4 & RatecodeID != 5)")
tiempo_distancia_positiva

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1780915,1,2025-01-20 12:07:18,2025-01-20 12:12:42,1.0,1.6,1.0,N,138,8,4,863372.12,6.75,0.5,0.0,0.0,1.0,863380.37,0.0,1.75,0.0

In [ ]:
# solo con RateCode 4 y 5
tarifas_especiales = datos_crudos[datos_crudos['RatecodeID'].isin([4, 5])]

resumen_tarifas = tarifas_especiales.groupby('RatecodeID')['fare_amount'].agg(['min', 'max', 'mean', 'count'])

resumen_tarifas.columns = ['Mínimo ($)', 'Máximo ($)', 'Promedio ($)', 'Total Viajes']

In [493]:
resumen_tarifas

            Mínimo ($)  Máximo ($)  Promedio ($)  Total Viajes
RatecodeID
4.0             -826.2      2450.9     94.662845          7092
5.0             -900.0       950.0     59.757875         26501

In [ ]:
# Definimos la lista de columnas que componen el total
columnas_suma = [
    'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
    'improvement_surcharge', 'congestion_surcharge', 'Airport_fee'
]

# Creamos una serie con la suma de esas columnas para cada fila
# .sum(axis=1) suma de forma horizontal (por fila)
suma_calculada = datos_crudos[columnas_suma].sum(axis=1)

discrepancias_total = datos_crudos[round(suma_calculada, 2) != round(datos_crudos['total_amount'], 2)]

# Ver cuántos errores de suma encontramos
print(f"Registros con descuadre en el total: {len(discrepancias_total)}")

##### Extra

In [507]:
print(datos_crudos.extra.shape[0])
print(datos_crudos.extra.value_counts().sum())
print(datos_crudos.extra.value_counts())

3475226
3475226
extra
 0.00     1764424
 1.00      537935
 2.50      532712
 3.25      200468
 5.00      109568
           ...
-2.00           1
 0.80           1
 1.01           1
 6.25           1
 13.25          1
Name: count, Length: 77, dtype: int64

##### Impuesto MTA_TAX

In [336]:
print(datos_crudos.mta_tax.shape[0])
print(datos_crudos.mta_tax.value_counts().sum())
print(datos_crudos.mta_tax.value_counts())
distancia_mayor =datos_crudos['mta_tax'].value_counts().sort_index(ascending=False)

3475226
3475226
mta_tax
 0.50     3379839
-0.50       57140
 0.00       38170
 1.00          64
 10.50          5
 4.75           3
 4.00           2
 3.75           2
 6.50           1
Name: count, dtype: int64

In [511]:
mta_negativo_05 = datos_crudos[datos_crudos['mta_tax'] > 0.5]
print(f'total porcentaje: {mta_negativo_05.shape[0]/datos_crudos.shape[0]*100:.3f}%')

total porcentaje: 0.002%

##### Tip_amount

In [512]:
print(datos_crudos.tip_amount.shape[0])
print(datos_crudos.tip_amount.value_counts().sum())
print(datos_crudos.tip_amount.value_counts())
propinas =datos_crudos['tip_amount'].value_counts().sort_index(ascending=False)

3475226
3475226
tip_amount
0.00     1118008
2.00      156750
1.00      120556
3.00       67562
5.00       39398
          ...
43.87          1
68.27          1
36.17          1
25.33          1
48.67          1
Name: count, Length: 4197, dtype: int64

In [514]:
# Propinas Negativas (Errores o ajustes)
propinas_negativas = datos_crudos[datos_crudos['tip_amount'] < 0]

# Propinas Positivas (Cualquier monto mayor a cero)
propinas_positivas = datos_crudos[datos_crudos['tip_amount'] > 0]

# Propinas Generosas (Superiores al 15% del fare_amount)
propinas_generosas = propinas_positivas[
    propinas_positivas['tip_amount'] > (propinas_positivas['total_amount'] * 0.2)
]

# Pagos en Efectivo (Cash)
# Nota: Aquí verás que la mayoría tiene tip_amount = 0
pagos_cash = datos_crudos[datos_crudos['payment_type'] == 2]

In [515]:
propinas_generosas

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
14,1,2025-01-01 00:39:55,2025-01-01 01:13:59,1.0,3.20,1.0,N,141,113,1,26.10,3.50,0.5,7.80,0.0,1.0,38.90,2.5,0.0,0.00
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.20,-1.00,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.00
28,2,2025-01-01 00:32:01,2025-01-01 00:46:43,1.0,3.06,1.0,N,90,246,1,17.70,1.00,0.5,10.00,0.0,1.0,32.70,2.5,0.0,0.00
30,2,2025-01-01 00:11:07,2025-01-01 00:23:29,3.0,3.98,1.0,N,140,79,1,19.10,1.00,0.5,6.03,0.0,1.0,30.13,2.5,0.0,0.00
51,2,2025-01-01 00:37:14,2025-01-01 00:42:58,4.0,1.01,1.0,N,107,170,1,7.90,1.00,0.5,3.23,0.0,1.0,16.13,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3472521,1,2025-01-31 23:20:35,2025-01-31 23:37:06,NaN,8.30,NaN,None,132,95,0,32.40,2.75,0.5,10.99,0.0,1.0,47.64,NaN,NaN,0.00
3473319,2,2025-01-31 23:05:00,2025-01-31 23:34:00,NaN,8.69,NaN,None,239,261,0,51.48,0.00,0.5,16.87,0.0,1.0,73.10,NaN,NaN,0.75
3473325,2,2025-01-31 23:37:10,2025-01-31 23:51:30,NaN,1.84,NaN,None,234,48,0,7.49,0.00,0.5,4.45,0.0,1.0,16.69,NaN,NaN,0.75
3473524,2,2025-01-31 23:30:19,2025-01-31 23:48:03,NaN,6.67,NaN,None,244,48,0,36.18,0.00,0.5,12.28,0.0,1.0,53.21,NaN,NaN,0.75
3474175,2,2025-01-31 23:59:02,2025-02-01 00:13:19,NaN,1.64,NaN,None,144,234,0,12.02,0.00,0.5,4.35,0.0,1.0,21.12,NaN,NaN,0.75

In [516]:
datos_crudos[datos_crudos['tip_amount'] == 400.00]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1583318,2,2025-01-17 23:31:29,2025-01-18 00:12:47,1.0,14.74,1.0,N,232,216,1,67.4,1.0,0.5,400.0,0.0,1.0,473.15,2.5,0.0,0.75

In [363]:
propinas_generosas.payment_type.value_counts()

payment_type
1    187079
0      1926
4       551
2       168
3        77
Name: count, dtype: int64

In [517]:
print(propinas_generosas.shape[0]/datos_crudos.shape[0]*100)

5.461544083751675

In [365]:
generosas_cash = propinas_generosas[propinas_generosas['payment_type'] == 2]
# no deberian estar registradas
print(f"Total de propinas generosas registradas en efectivo: {len(generosas_cash)}")

Total de propinas generosas registradas en efectivo: 168

In [366]:
generosas_cash.VendorID.value_counts()

VendorID
2    168
Name: count, dtype: int64

In [367]:
# Filtramos donde la propina es estrictamente mayor al costo del viaje
propinas_excesivas = datos_crudos[
    (datos_crudos['tip_amount'] > datos_crudos['fare_amount']) & 
    (datos_crudos['tip_amount'] > 0) & 
    (datos_crudos['fare_amount'] > 0)
]

In [368]:
propinas_excesivas

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
426,1,2025-01-01 00:27:24,2025-01-01 00:35:02,1.0,0.70,1.0,N,113,234,1,8.60,3.5,0.5,10.00,0.00,1.0,23.60,2.5,0.00,0.00
482,2,2025-01-01 00:01:41,2025-01-01 00:15:29,1.0,7.15,1.0,N,138,80,1,29.60,6.0,0.5,40.00,0.00,1.0,78.85,0.0,1.75,0.00
1439,2,2025-01-01 00:43:36,2025-01-01 00:51:58,1.0,1.14,1.0,N,237,237,1,10.00,1.0,0.5,20.00,0.00,1.0,35.00,2.5,0.00,0.00
1445,2,2025-01-01 00:57:03,2025-01-01 01:54:51,4.0,4.95,4.0,N,161,265,1,35.20,1.0,0.5,46.42,13.38,1.0,100.00,2.5,0.00,0.00
1669,2,2025-01-01 00:54:42,2025-01-01 00:58:53,1.0,1.06,1.0,N,236,263,1,7.20,1.0,0.5,15.00,0.00,1.0,27.20,2.5,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3408953,2,2025-01-29 12:21:00,2025-01-29 12:41:00,NaN,1.46,NaN,None,230,163,0,2.30,0.0,0.5,3.41,0.00,1.0,10.46,NaN,NaN,0.75
3427923,1,2025-01-30 10:31:59,2025-01-30 10:41:19,NaN,1.10,NaN,None,263,141,0,8.60,0.0,0.5,12.72,0.00,1.0,25.32,NaN,NaN,0.00
3429068,2,2025-01-30 13:33:13,2025-01-30 13:39:33,NaN,1.44,NaN,None,50,142,0,3.40,0.0,0.5,3.63,0.00,1.0,11.78,NaN,NaN,0.75
3445741,2,2025-01-31 04:41:52,2025-01-31 04:49:57,NaN,5.41,NaN,None,226,138,0,24.58,0.0,0.5,30.00,0.00,1.0,56.08,NaN,NaN,0.00
3450550,2,2025-01-31 10:06:03,2025-01-31 10:21:02,NaN,1.38,NaN,None,141,161,0,13.58,0.0,0.5,20.00,0.00,1.0,38.33,NaN,NaN,0.75

In [369]:
propinas_excesivas.improvement_surcharge.value_counts()

improvement_surcharge
1.0    4289
Name: count, dtype: int64

In [370]:
print(propinas_excesivas.shape[0]/datos_crudos.shape[0]*100)

0.12341643392400956

##### tolls_amount

In [371]:
print(datos_crudos.tolls_amount.shape[0])
print(datos_crudos.tolls_amount.value_counts().sum())
print(datos_crudos.tolls_amount.value_counts())
peaje =datos_crudos['tolls_amount'].value_counts().sort_index(ascending=False)

3475226
3475226
tolls_amount
 0.00     3259590
 6.94      192386
-6.94        3738
 14.06       2249
 3.18        1689
           ...
 3.96           1
 51.38          1
 6.80           1
 19.89          1
 23.76          1
Name: count, Length: 1234, dtype: int64

In [372]:
peaje

tolls_amount
 170.94    1
 126.94    1
 123.00    1
 105.88    1
 96.94     1
          ..
-48.28     1
-74.76     1
-82.69     1
-96.94     1
-126.94    1
Name: count, Length: 1234, dtype: int64

In [373]:
peajes_negativos = datos_crudos[datos_crudos['tolls_amount'] < 0]
print(peajes_negativos.shape[0])
peajes_negativos.head()

4559

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
822,2,2025-01-01 00:49:36,2025-01-01 02:11:46,4.0,24.70,1.0,N,68,82,3,-111.5,-1.0,-0.5,0.0,-6.94,-1.0,-123.44,-2.5,0.00,0.0
1061,2,2025-01-01 00:05:15,2025-01-01 00:23:39,1.0,7.79,1.0,N,138,24,4,-32.4,-6.0,-0.5,0.0,-6.94,-1.0,-48.59,0.0,-1.75,0.0
3425,2,2025-01-01 00:33:51,2025-01-01 01:07:12,2.0,19.60,2.0,N,132,238,2,-70.0,0.0,-0.5,0.0,-6.94,-1.0,-80.19,0.0,-1.75,0.0
3579,2,2025-01-01 00:38:09,2025-01-01 01:16:04,1.0,19.66,1.0,N,234,210,4,-76.5,-1.0,-0.5,0.0,-6.94,-1.0,-88.44,-2.5,0.00,0.0
4041,2,2025-01-01 00:16:59,2025-01-01 00:47:34,4.0,19.66,1.0,N,48,80,2,-74.4,-1.0,-0.5,0.0,-6.94,-1.0,-86.34,-2.5,0.00,0.0

In [374]:
peajes_negativos.VendorID.value_counts()

VendorID
2    4559
Name: count, dtype: int64

In [375]:
anulaciones_totales = peajes_negativos[peajes_negativos['fare_amount'] < 0]
print(anulaciones_totales.shape[0])
print(peajes_negativos.shape[0]/datos_crudos.shape[0]*100)

4559
0.1311857128140731

##### improvement_surcharge

In [376]:
print(datos_crudos.improvement_surcharge.shape[0])
print(datos_crudos.improvement_surcharge.value_counts().sum())
print(datos_crudos.improvement_surcharge.value_counts())
recargo_mejora =datos_crudos['improvement_surcharge'].value_counts().sort_index(ascending=False)

3475226
3475226
improvement_surcharge
 1.0    3377509
-1.0      59530
 0.0      37694
 0.3        493
Name: count, dtype: int64

In [377]:
recargo_mejora

improvement_surcharge
 1.0    3377509
 0.3        493
 0.0      37694
-1.0      59530
Name: count, dtype: int64

In [378]:
recargo_negativos = datos_crudos[datos_crudos['improvement_surcharge'] < 0]
print(recargo_negativos.shape[0])
recargo_negativos.head()

59530

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.2,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.0
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.5,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.0
104,2,2025-01-01 00:56:12,2025-01-01 01:15:00,1.0,0.97,1.0,N,161,170,4,-16.3,-1.0,-0.5,0.00,0.0,-1.0,-21.30,-2.5,0.0,0.0
149,2,2025-01-01 00:55:53,2025-01-01 01:06:49,1.0,1.42,1.0,N,79,45,2,-12.1,-1.0,-0.5,0.00,0.0,-1.0,-17.10,-2.5,0.0,0.0
202,2,2025-01-01 00:29:35,2025-01-01 00:36:02,1.0,0.60,1.0,N,79,148,4,-7.2,-1.0,-0.5,0.00,0.0,-1.0,-12.20,-2.5,0.0,0.0

In [ ]:

mejora_uno = datos_crudos[datos_crudos['improvement_surcharge'] == 1]

print(f"Registros con recargo de $1.00: {len(mejora_uno)}")

print("\nDistribución por VendorID:")
print(mejora_uno['VendorID'].value_counts())

print("\nDistribución por RateCodeID (1=Estandar):")
print(mejora_uno['RatecodeID'].value_counts())

mejora_negativa = datos_crudos[datos_crudos['improvement_surcharge'] < 0]
anulaciones_confirmadas = mejora_negativa[mejora_negativa['fare_amount'] == 0]

print(f"\nRecargos negativos que son anulaciones de viaje: {len(anulaciones_confirmadas)}")

Registros con recargo de $1.00: 3377509

Distribución por VendorID:
VendorID
2    2660064
1     716239
7       1206
Name: count, dtype: int64

Distribución por RateCodeID (1=Estandar):
RatecodeID
1.0     2702665
2.0       90757
5.0       24878
3.0        7912
4.0        6633
99.0       5427
6.0           7
Name: count, dtype: int64

Recargos negativos que son anulaciones de viaje: 224

In [380]:
porcentaje_uno = (mejora_uno.shape[0] / datos_crudos.shape[0]) * 100
print(f"El valor erróneo de $1.00 representa el {porcentaje_uno:.4f}% del dataset.")

El valor erróneo de $1.00 representa el 97.1882% del dataset.

In [381]:
recargo_mejora_negativa = datos_crudos[datos_crudos['improvement_surcharge'] < 0]
anulaciones_totales = recargo_mejora_negativa[recargo_mejora_negativa['fare_amount'] < 0]
print(anulaciones_totales.shape[0])
print(anulaciones_totales.shape[0]/datos_crudos.shape[0]*100)

anulaciones_totales.head()

59306
1.7065364957559594

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.2,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.0
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.5,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.0
104,2,2025-01-01 00:56:12,2025-01-01 01:15:00,1.0,0.97,1.0,N,161,170,4,-16.3,-1.0,-0.5,0.00,0.0,-1.0,-21.30,-2.5,0.0,0.0
149,2,2025-01-01 00:55:53,2025-01-01 01:06:49,1.0,1.42,1.0,N,79,45,2,-12.1,-1.0,-0.5,0.00,0.0,-1.0,-17.10,-2.5,0.0,0.0
202,2,2025-01-01 00:29:35,2025-01-01 00:36:02,1.0,0.60,1.0,N,79,148,4,-7.2,-1.0,-0.5,0.00,0.0,-1.0,-12.20,-2.5,0.0,0.0

In [382]:
anulaciones_totales.VendorID.value_counts()

VendorID
2    59306
Name: count, dtype: int64

##### total_amount

In [383]:
print(datos_crudos.total_amount.shape[0])
print(datos_crudos.total_amount.value_counts().sum())
print(datos_crudos.total_amount.value_counts())
total_pagado =datos_crudos['total_amount'].value_counts().sort_index(ascending=False)

3475226
3475226
total_amount
17.70     23391
12.60     21030
21.90     18725
13.50     18309
16.86     18087
          ...
125.43        1
82.53         1
142.67        1
195.43        1
86.07         1
Name: count, Length: 21995, dtype: int64

In [384]:
total_pagado

total_amount
 863380.37    1
 2506.71      1
 1311.70      1
 969.05       1
 953.50       1
             ..
-701.00       3
-704.25       1
-851.00       1
-865.39       1
-901.00       1
Name: count, Length: 21995, dtype: int64

In [385]:
total_negativos = datos_crudos[datos_crudos['total_amount'] < 0]
total_negativos.VendorID.value_counts()

VendorID
2    63037
Name: count, dtype: int64

In [386]:
print(f"Porcentaje de negativos: {total_negativos.shape[0]/datos_crudos.shape[0]*100:.2f}%")

Porcentaje de negativos: 1.81%

In [387]:
total_negativos_anulados = total_negativos[total_negativos['trip_distance'] <= 0]
total_negativos_anulados.shape[0]
print(f"Porcentaje de negativos: {total_negativos_anulados.shape[0]/datos_crudos.shape[0]*100:.2f}%")

Porcentaje de negativos: 0.13%

In [388]:
total_negativos_anulados.trip_distance.value_counts()

trip_distance
0.0    4526
Name: count, dtype: int64

##### congestion surcharge

In [389]:
print(datos_crudos.congestion_surcharge.shape[0])
print(datos_crudos.congestion_surcharge.value_counts().sum())
print(datos_crudos.congestion_surcharge.value_counts())
recargo_congestion =datos_crudos['congestion_surcharge'].value_counts().sort_index(ascending=False)

3475226
2935077
congestion_surcharge
 2.5    2660818
 0.0     225938
-2.5      48321
Name: count, dtype: int64

In [390]:
recargo_congestion_negativo = datos_crudos[datos_crudos['congestion_surcharge'] < 0]
recargo_congestion_negativo_anulacion = recargo_congestion_negativo[recargo_congestion_negativo['trip_distance'] <= 0]
recargo_congestion_negativo_anulacion.shape[0]
print(f"Porcentaje de negativos: {recargo_congestion_negativo.shape[0]/datos_crudos.shape[0]*100:.2f}%")
print(f"Porcentaje de negativos anulados: {recargo_congestion_negativo_anulacion.shape[0]/datos_crudos.shape[0]*100:.2f}%")

Porcentaje de negativos: 1.39%
Porcentaje de negativos anulados: 0.07%

In [391]:
recargo_congestion_negativo_anulacion.trip_distance.value_counts()

trip_distance
0.0    2501
Name: count, dtype: int64

In [392]:
recargo_congestion_negativo

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.2,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.00
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.5,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.00
104,2,2025-01-01 00:56:12,2025-01-01 01:15:00,1.0,0.97,1.0,N,161,170,4,-16.3,-1.0,-0.5,0.00,0.0,-1.0,-21.30,-2.5,0.0,0.00
149,2,2025-01-01 00:55:53,2025-01-01 01:06:49,1.0,1.42,1.0,N,79,45,2,-12.1,-1.0,-0.5,0.00,0.0,-1.0,-17.10,-2.5,0.0,0.00
202,2,2025-01-01 00:29:35,2025-01-01 00:36:02,1.0,0.60,1.0,N,79,148,4,-7.2,-1.0,-0.5,0.00,0.0,-1.0,-12.20,-2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934953,2,2025-01-31 23:31:24,2025-01-31 23:34:04,1.0,0.51,1.0,N,162,170,2,-5.1,-1.0,-0.5,0.00,0.0,-1.0,-10.85,-2.5,0.0,-0.75
2934960,2,2025-01-31 23:41:22,2025-01-31 23:43:05,1.0,0.04,1.0,N,263,263,3,-3.7,-1.0,-0.5,0.00,0.0,-1.0,-8.70,-2.5,0.0,0.00
2934985,2,2025-01-31 23:03:01,2025-01-31 23:04:47,1.0,0.40,1.0,N,236,236,4,-4.4,-1.0,-0.5,0.00,0.0,-1.0,-9.40,-2.5,0.0,0.00
2935015,2,2025-01-31 23:14:54,2025-01-31 23:23:48,2.0,1.08,1.0,N,114,158,3,-9.3,-1.0,-0.5,0.00,0.0,-1.0,-15.05,-2.5,0.0,-0.75
2935039,2,2025-01-31 23:14:15,2025-02-01 00:01:45,1.0,7.09,1.0,N,234,17,4,-44.3,-1.0,-0.5,0.00,0.0,-1.0,-50.05,-2.5,0.0,-0.75

In [393]:
recargo_congestion_negativo.VendorID.value_counts()
print(len(recargo_congestion_negativo[recargo_congestion_negativo['fare_amount'] <= 0]))

48321

In [394]:
recargo_congestion_nulo = datos_crudos[datos_crudos['congestion_surcharge'].isnull()]
print(f"Porcentaje nulos: {datos_crudos.congestion_surcharge.isnull().sum()/datos_crudos.shape[0]*100:.2f}%")

Porcentaje nulos: 15.54%

In [395]:
recargo_congestion_nulo

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,2.32,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,6.02,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,22.72,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,-2.35,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,5.06,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [396]:
recargo_congestion_nulo.store_and_fwd_flag.value_counts()

Series([], Name: count, dtype: int64)

##### Airport_fee

In [397]:
print(datos_crudos.Airport_fee.shape[0])
print(datos_crudos.Airport_fee.value_counts().sum())
print(datos_crudos.Airport_fee.value_counts())
aeropuerto_esp =datos_crudos['Airport_fee'].value_counts().sort_index(ascending=False)

3475226
2935077
Airport_fee
 0.00    2706446
 1.75     218203
-1.75      10411
 1.25          8
 5.00          7
 0.75          1
 6.75          1
Name: count, dtype: int64

In [398]:
aeropuerto_esp_negativo = datos_crudos[datos_crudos['Airport_fee']<0]
aeropuerto_esp_negativo.shape[0]
print(f"porcentaje neagtivos: {aeropuerto_esp_negativo.shape[0]/datos_crudos.shape[0]*100:.2f}%")

porcentaje neagtivos: 0.30%

In [399]:
aeropuerto_esp_negativo.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1061,2,2025-01-01 00:05:15,2025-01-01 00:23:39,1.0,7.79,1.0,N,138,24,4,-32.4,-6.0,-0.5,0.0,-6.94,-1.0,-48.59,0.0,-1.75,0.0
1231,2,2025-01-01 00:30:37,2025-01-01 01:04:46,1.0,16.70,1.0,N,132,225,4,-66.0,-1.0,-0.5,0.0,0.00,-1.0,-70.25,0.0,-1.75,0.0
2028,2,2025-01-01 00:08:22,2025-01-01 00:10:16,2.0,0.03,1.0,N,138,138,4,-3.7,-6.0,-0.5,0.0,0.00,-1.0,-12.95,0.0,-1.75,0.0
2659,2,2025-01-01 00:15:00,2025-01-01 00:30:09,1.0,5.58,1.0,N,132,215,3,-24.0,-1.0,-0.5,0.0,0.00,-1.0,-28.25,0.0,-1.75,0.0
2826,2,2025-01-01 00:12:24,2025-01-01 00:49:59,2.0,15.24,1.0,N,132,149,2,-61.8,-1.0,-0.5,0.0,0.00,-1.0,-66.05,0.0,-1.75,0.0

In [400]:
#len(aeropuerto_esp_negativo[aeropuerto_esp_negativo['trip_distance']==0])
aeropuerto_esp_negativo.VendorID.value_counts()

VendorID
2    10411
Name: count, dtype: int64

In [401]:
aeropuerto_esp_nulo = datos_crudos[datos_crudos['Airport_fee'].isnull()]
aeropuerto_esp_nulo.shape[0]
print(f"porcentaje nulos: {aeropuerto_esp_nulo.shape[0]/datos_crudos.shape[0]*100:.2f}%")

porcentaje nulos: 15.54%

In [402]:
aeropuerto_esp_nulo

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2935077,2,2025-01-01 00:39:17,2025-01-01 01:10:42,NaN,6.75,NaN,None,48,42,0,2.32,0.0,0.5,0.0,0.0,1.0,14.90,NaN,NaN,0.00
2935078,2,2025-01-01 00:33:40,2025-01-01 01:10:34,NaN,3.88,NaN,None,4,48,0,6.02,0.0,0.5,0.0,0.0,1.0,10.02,NaN,NaN,0.00
2935079,1,2025-01-01 00:09:32,2025-01-01 00:12:38,NaN,0.00,NaN,None,158,158,0,22.72,0.0,0.5,0.0,0.0,1.0,26.72,NaN,NaN,0.00
2935080,2,2025-01-01 00:21:42,2025-01-01 00:36:29,NaN,3.55,NaN,None,137,211,0,-2.35,0.0,0.5,0.0,0.0,1.0,5.80,NaN,NaN,0.00
2935081,2,2025-01-01 00:56:04,2025-01-01 01:06:11,NaN,1.55,NaN,None,140,233,0,5.06,0.0,0.5,0.0,0.0,1.0,9.06,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.0,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.0,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.0,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.0,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.0,0.0,1.0,16.09,NaN,NaN,0.00

In [403]:
aeropuerto_esp_nulo.payment_type.value_counts()

payment_type
0    540149
Name: count, dtype: int64

##### CBD_CONGESTION_FEE

In [307]:
print(datos_crudos.cbd_congestion_fee.shape[0])
print(datos_crudos.cbd_congestion_fee.value_counts().sum())
print(datos_crudos.cbd_congestion_fee.value_counts())
alivio_congestion =datos_crudos['cbd_congestion_fee'].value_counts().sort_index(ascending=False)

3475226
3475226
cbd_congestion_fee
 0.75    2246495
 0.00    1222178
-0.75       6553
Name: count, dtype: int64

In [314]:
alivio_congestion_negativo = datos_crudos[datos_crudos['cbd_congestion_fee']<0]
alivio_congestion_negativo.shape[0]
print(f"porcentaje neagtivos global: {alivio_congestion_negativo.shape[0]/datos_crudos.shape[0]*100:.2f}%")

porcentaje neagtivos global: 0.19%

In [312]:
alivio_congestion_negativo_devolucion = alivio_congestion_negativo[alivio_congestion_negativo['trip_distance']==0]
alivio_congestion_negativo_devolucion.shape[0]
print(f"porcentaje neagtivos devolucion: {alivio_congestion_negativo_devolucion.shape[0]/alivio_congestion_negativo.shape[0]*100:.2f}%")

porcentaje neagtivos devolucion: 4.87%

In [320]:
len(alivio_congestion_negativo[alivio_congestion_negativo['total_amount']<0])

6553